# GitHub Pages Configuration for Recursive Control

# Site settings
title: Recursive Control Documentation
description: AI-Powered Computer Control for Windows
baseurl: "/Recursive-Control"
url: "https://flowdevs-io.github.io"

theme: null

# Plugins (GitHub Pages whitelist)
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Sass pipeline
sass:
  sass_dir: _sass
  style: compressed

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Show downloads button
show_downloads: false
